# Generated by Django 3.2.19 on 2023-06-22 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0003_auto_20201021_0811'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policy',
            options={'managed': True},
        ),
    ]
