# Generated by Django 3.2.18 on 2023-05-12 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0006_auto_20240716_1744'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policy',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='policyrenewal',
            options={'managed': True},
        ),
    ]