# Generated by Django 4.2.17 on 2025-03-04 10:19


from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0007_fix_policy_mutation_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='policyrenewal',
            constraint=models.UniqueConstraint(
                fields=['policy', 'validity_to'], 
                name='unique_policy_validity_to_null',
                condition=models.Q(validity_to__isnull=True)
            )
        ),
    ]
    
