# Generated by Django 4.2.17 on 2025-03-04 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0007_fix_policy_mutation_name'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE UNIQUE INDEX unique_policy_validity_to_null
            ON dbo.tblPolicyRenewals (PolicyID, ValidityTo)
            WHERE ValidityTo IS NULL;
            """,
            reverse_sql="DROP INDEX unique_policy_validity_to_null ON dbo.tblPolicyRenewals;"
        ),
    ]

