# Generated by Django 4.2.25 on 2026-01-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0009_add_constraint_policyrenewal'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='pregnancy_age',
            field=models.PositiveSmallIntegerField(blank=True, db_column='PregnancyAge', null=True),
        ),
    ]
