# Generated by Django 4.2.16 on 2025-04-24 10:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_moduleconfiguration_module'),
        ('policy', '0010_policy_payment_day_policy_periodicity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankImport',
            fields=[
                ('idBankImport', models.AutoField(primary_key=True, serialize=False)),
                ('importDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('stored_file', models.FileField(blank=True, null=True, upload_to='bankImports/%Y/%m/')),
                ('user', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.DO_NOTHING, to='core.interactiveuser')),
            ],
            options={
                'db_table': 'tblBankImport',
            },
        ),
    ]
